# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simon/dev/diagrammer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simon/dev/diagrammer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/dev/diagrammer/CMakeFiles /home/simon/dev/diagrammer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/dev/diagrammer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Diagrammer

# Build rule for target.
Diagrammer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Diagrammer
.PHONY : Diagrammer

# fast build rule for target.
Diagrammer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Diagrammer.dir/build.make CMakeFiles/Diagrammer.dir/build
.PHONY : Diagrammer/fast

#=============================================================================
# Target rules for targets named DiagrammerLib

# Build rule for target.
DiagrammerLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DiagrammerLib
.PHONY : DiagrammerLib

# fast build rule for target.
DiagrammerLib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/DiagrammerLib.dir/build.make src/CMakeFiles/DiagrammerLib.dir/build
.PHONY : DiagrammerLib/fast

tests/basic.o: tests/basic.cpp.o
.PHONY : tests/basic.o

# target to build an object file
tests/basic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Diagrammer.dir/build.make CMakeFiles/Diagrammer.dir/tests/basic.cpp.o
.PHONY : tests/basic.cpp.o

tests/basic.i: tests/basic.cpp.i
.PHONY : tests/basic.i

# target to preprocess a source file
tests/basic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Diagrammer.dir/build.make CMakeFiles/Diagrammer.dir/tests/basic.cpp.i
.PHONY : tests/basic.cpp.i

tests/basic.s: tests/basic.cpp.s
.PHONY : tests/basic.s

# target to generate assembly for a file
tests/basic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Diagrammer.dir/build.make CMakeFiles/Diagrammer.dir/tests/basic.cpp.s
.PHONY : tests/basic.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Diagrammer.dir/build.make CMakeFiles/Diagrammer.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Diagrammer.dir/build.make CMakeFiles/Diagrammer.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Diagrammer.dir/build.make CMakeFiles/Diagrammer.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Diagrammer"
	@echo "... DiagrammerLib"
	@echo "... tests/basic.o"
	@echo "... tests/basic.i"
	@echo "... tests/basic.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

